### ISSUE TITLE
Tick DDMMYYY

### ISSUE THREAD

**Issue by simplevulnerabilitymanager** [tomas-rampas/Dukas.Net#1]
Hello,
Can you convert tick values (* .csv) to YYYY.MM.DD?
![image](https://user-images.githubusercontent.com/23158753/149343518-5cf4d9f1-e666-4eed-b2fd-738a2eeaf9fe.png)

**Comment by tomas-rampas** [comment]
Hi @simplevulnerabilitymanager,
I agree, I'm gonna change the date format to what you've suggested as default, with an option to redefine the date format as a command line param.

**Comment by tomas-rampas** [comment]
I consolidated date format in Tick and Bar to be the same yyyy-MM-dd HH:mm:ss.fff (franctional second only applies for ticks)
