### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by awakanto** [tomas-rampas/Dukas.Net#2]
Hi, thanks for all the effort that you have put into this. From the description this seems to be the only DukasCopy downloader that can download OHLCV Seconds Data in csv format. The only issue that I have is: How do I use it? Would you be kind enough (again), to state how a user may go about using this?

Thank you.

**Comment by tomas-rampas** [comment]
Hi,
dukas.net -s "2020-01-01 00:00:00" -e "2020-12-31 23:59:59" -p DEUIDXEUR,GBRIDXGBP,USA30IDXUSD,AUSIDXAUD,LIGHTCMDUSD -o "e:\temp" -q Both --major-scale Min --minor-scale 1 --file-scale Day --header -g

Please follow the 
All is described in readme file. Please let me know, if it's unclear or wrong. I'll update accordingly.

**Comment by awakanto** [comment]
Hi thanks for the reply. The question was in relation to installation instructions. There was no installation instructions. I googled and figured it out. Thanks
